version: '3.7'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5433:5432
    environment:
      - POSTGRES_USER=toubib
      - POSTGRES_PASSWORD=toubibPass123
      - POSTGRES_DB=toubibdb

  db_test:
    image: postgres:15-alpine
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    expose:
      - 5434:5432
    environment:
      - POSTGRES_USER=toubib
      - POSTGRES_PASSWORD=toubibPass123
      - POSTGRES_DB=toubibdb_test

volumes:
  postgres_data:
  postgres_data_test:
